/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DemoMachine {}
}

declare global {


  interface HTMLDemoMachineElement extends Components.DemoMachine, HTMLStencilElement {}
  var HTMLDemoMachineElement: {
    prototype: HTMLDemoMachineElement;
    new (): HTMLDemoMachineElement;
  };
  interface HTMLElementTagNameMap {
    'demo-machine': HTMLDemoMachineElement;
  }
}

declare namespace LocalJSX {
  interface DemoMachine extends JSXBase.HTMLAttributes<HTMLDemoMachineElement> {}

  interface IntrinsicElements {
    'demo-machine': DemoMachine;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


